version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../workspaces:/app/workspaces
      - ../logs:/app/logs
    command: ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "8000"]

  duckdb:
    image: ghcr.io/duckdb/duckdb-wasm:latest
    restart: unless-stopped
    command: ["/bin/true"]
