services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../workspaces:/app/workspaces
      - ../logs:/app/logs
    command: ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://app:8000
    ports:
      - "3000:3000"
    depends_on:
      - app
